[tool.poetry]
name = "aulas"
version = "0.1.0"
description = ""
authors = ["juvenalculino <b831381@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.19"
flet = "^0.23.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
